sonar.projectKey=invariantcontinuum_agentctl
sonar.organization=invariantcontinuum
sonar.projectName=agentctl
sonar.sources=cmd,internal
sonar.tests=internal
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
